version: '3'
services:
  backend:
    build:
      context: "./LearnSwift/LearnSwift"
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user 
      SPRING_DATASOURCE_PASSWORD: password 
    networks:
      - app-network

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    environment:
      API_URL: "http://backend:8080"  
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

