package com.example.LearnSwift.Model;

import com.fasterxml.jackson.annotation.*;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalTime;

@Entity //This annotation specifies that the class is an entity and is mapped to a database table
public class Booking {

    @Id //the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)  //automatically generated by the database
    private Long booking_id;

    @ManyToOne (fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id")
    @JsonProperty("course")
    @JsonBackReference("course_booking")
    private Course course;

    //the relationships between bookings with students and instructors. With the cascade we ensure that any booking change will also apply to students and instructors
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id")
    @JsonBackReference("student_booking") //to prevent infinite recursion
    private Student student;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "instructor_id")
    @JsonBackReference ("instructor_booking") //to prevent infinite recursion
    private Instructor instructor;
    @JsonFormat(pattern = "yyyy-MM-dd") //for dates
    @JsonProperty
    private LocalDate bookingDate;
    @JsonProperty
    private String booking_status;
    @JsonProperty
    @JsonFormat(pattern = "HH:mm")
    private LocalTime startTime;
    @JsonFormat(pattern = "HH:mm")
    @JsonProperty
    private LocalTime endTime;

    public Booking(Student student, Instructor instructor, Course course, LocalDate bookingDate, String booking_status, LocalTime startTime, LocalTime endTime) {
        this.student = student;
        this.instructor = instructor;
        this.course = course;
        this.bookingDate = bookingDate;
        this.booking_status = booking_status;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Booking() {
    }

    //GETTERS
    public Long getBooking_id() {
        return booking_id;
    }

    public Course getCourse() {
        return course;
    }

    public String getCourse_title() {
        return course.getTitle();
    }

    public String getInstructorUsername() {return instructor.getUsername();}

    public Student getStudent() {
        return student;
    }

    public Instructor getInstructor() {
        return instructor;
    }

    public LocalDate getBookingDate() {
        return bookingDate;
    }

    public String getBooking_status() {
        return booking_status;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    //SETTERS

    public void setBooking_id(Long booking_id) {
        this.booking_id = booking_id;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }

    public void setBookingDate(LocalDate bookingDate) {
        this.bookingDate = bookingDate;
    }

    public void setBooking_status(String booking_status) {
        this.booking_status = booking_status;
    }

    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    @Override
    public String toString() {
        return "Booking{" +
                "booking_id=" + booking_id +
                ", course=" + (course != null ? "Course{course_id=" + course.getCourse_id() + ", title=" + course.getTitle() + "}" : "null") +
                ", student=" + (student != null ? "Student{student_id=" + student.getUser_id() + ", username=" + student.getUsername() + "}" : "null") +
                ", instructor=" + (instructor != null ? "Instructor{instructor_id=" + instructor.getUser_id() + ", username=" + instructor.getUsername() + "}" : "null") +
                ", bookingDate=" + bookingDate +
                ", booking_status='" + booking_status + '\'' +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                '}';
    }
}
