package com.example.LearnSwift.Model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

import java.util.Date;

@Entity //This annotation specifies that the class is an entity and is mapped to a database table
public class Review {
    @Id //the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)  //automatically generated by the database
    private Long review_id;
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL) //With the cascade we ensure that any instructor change will also apply to courses
    @JoinColumn(name = "instructor_id") // define the foreign key column in the collection table that will refer to the primary key
    @JsonBackReference("instructor_review") //to prevent infinite recursion
    private Instructor instructor;
    private String studentName;
    private int rating;
    private String comment;
    private Date review_date;

    public Review(Instructor instructor, String studentName, int rating, String comment, Date review_date) {
        this.instructor = instructor;
        this.studentName= studentName;
        this.rating = rating;
        this.comment = comment;
        this.review_date = review_date;
    }

    public Review() {
    }

    //GETTERS

    public Long getReview_id() {
        return review_id;
    }

    public Instructor getInstructor() {
        return instructor;
    }

    public String getStudentName() {
        return studentName;
    }

    public int getRating() {
        return rating;
    }

    public String getComment() {
        return comment;
    }

    public Date getReview_date() {
        return review_date;
    }

    //SETTERS

    public void setReview_id(Long review_id) {
        this.review_id = review_id;
    }

    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public void setReview_date(Date review_date) {
        this.review_date = review_date;
    }
}
